### ISSUE TITLE
新增的两项协议均无法正常工作

### ISSUE THREAD

**Issue by w-tim** [qinyuhang/ShadowsocksX-NG#60]
谢谢楼主的客户端。macOS 10.12.1  1.3.5R8build1测试了一下午，新增的两个协议均无法正常工作。手机端测试一切顺利。

**Comment by w-tim** [comment]
谢谢快速更新，测试了1.3.7 R8build1，still not working 应该还有错

**Comment by clockcloud** [comment]
同样问题。卸载，删除资源库和private下相关文件后安装旧版本依然无法使用。

**Comment by clockcloud** [comment]
Process:               ss-local [3091]
Path:                  /Users/USER/Library/Application Support/ShadowsocksX-NG/*/ss-local
Identifier:            ss-local
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           ss-local [3091]
User ID:               502

Date/Time:             2016-10-31 09:31:36.767 +0800
OS Version:            Mac OS X 10.12.1 (16B2555)
Report Version:        12
Anonymous UUID:        F22B88A3-4F29-DE79-732D-DC59C4B885CC


Time Awake Since Boot: 1600 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/Users/zhongyun/Library/Application Support/ShadowsocksX-NG/

Dyld Error Message:
  Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /Users/USER/Library/Application Support/ShadowsocksX-NG/ss-local
  Reason: image not found

Binary Images:
       0x10c837000 -        0x10c877ff3 +ss-local (0) <CA51637C-8267-35BF-AD5C-A718C238E59F> /Users/USER/Library/Application Support/ShadowsocksX-NG/ss-local
       0x110832000 -        0x11086f287  dyld (421.2) <13A9466A-2576-3ABB-AD9D-D6BC16439B8F> /usr/lib/dyld
    0x7fff89b08000 -     0x7fff89becff3  libcrypto.0.9.8.dylib (64) <4CB423CE-0B86-334A-9335-FEE75198024F> /usr/lib/libcrypto.0.9.8.dylib

**Comment by clockcloud** [comment]
brew uninstall pcre
brew install pcre
解决。。。

**Comment by qinyuhang** [comment]
终端试试：  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" && brew update && brew install pcre

**Comment by w-tim** [comment]
谢谢分享解决方案

最终依靠 brew install pcre 解决
